name: Build and Release Android APK

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build Android APK
        run: eas build --platform android --profile preview --non-interactive --no-wait

      - name: Wait for build to complete
        id: build
        run: |
          BUILD_ID=$(eas build:list --platform=android --limit=1 --json | jq -r '.[0].id')
          echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT

          # Wait for build to complete (timeout after 30 minutes)
          timeout=1800
          elapsed=0
          while [ $elapsed -lt $timeout ]; do
            STATUS=$(eas build:view $BUILD_ID --json | jq -r '.status')
            echo "Build status: $STATUS"

            if [ "$STATUS" = "finished" ]; then
              echo "Build completed successfully!"
              break
            elif [ "$STATUS" = "errored" ] || [ "$STATUS" = "canceled" ]; then
              echo "Build failed with status: $STATUS"
              exit 1
            fi

            sleep 30
            elapsed=$((elapsed + 30))
          done

          if [ $elapsed -ge $timeout ]; then
            echo "Build timed out after 30 minutes"
            exit 1
          fi

      - name: Download APK
        run: |
          BUILD_ID=${{ steps.build.outputs.build_id }}
          APK_URL=$(eas build:view $BUILD_ID --json | jq -r '.artifacts.buildUrl')
          curl -L -o vc-tkn-app.apk "$APK_URL"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: vc-tkn-app.apk
          body: |
            ## Android APK Release

            Download and install the APK on your Android device.

            **Note:** You may need to enable "Install from Unknown Sources" in your device settings.

            ### Installation
            1. Download `vc-tkn-app.apk`
            2. Transfer to your Android device
            3. Open the file and follow installation prompts
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
